openapi: 3.0.3
info:
  title: Newsfeed API
  version: 1.0.0
  description: API for News Posts (Create, Read, Update, Delete) and Version History.
servers:
  - url: /
tags:
  - name: Newsfeed
    description: Newspost Operations

paths:
  /newsfeed:
    post:
      tags: [Newsfeed]
      summary: Create Newspost
      description: Creates a new news post.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsPostCreate'
      responses:
        '200':
          description: News post created
    get:
      tags: [Newsfeed]
      summary: Read Newspost (List)
      description: Reads a paginated list of news posts, optionally filtered by search term and/or date.
      parameters:
        - in: query
          name: query
          description: Optional search term to find in title and summary.
          required: false
          schema:
            type: string
          example: "Test"
        - in: query
          name: from
          description: Optional start date to get posts from this point in time.
          required: false
          schema:
            type: string
            format: date-time
          example: "2025-09-13"
        - in: query
          name: to
          description: Optional end date to get posts up to this point in time.
          required: false
          schema:
            type: string
            format: date-time
          example: "2025-09-18"
        - in: query
          name: page
          description: The page number to retrieve (starting at 0).
          required: true
          schema:
            type: integer
            minimum: 0
          example: 1
        - in: query
          name: pageSize
          description: The number of entries per page.
          required: true
          schema:
            type: integer
            minimum: 1
          example: 10
      responses:
        '200':
          description: List of news posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewsPostRead'

  /newsfeed/{id}:
    put:
      tags: [Newsfeed]
      summary: Update Newspost
      description: Updates an existing news post by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsPostUpdate'
      responses:
        '200':
          description: News post updated
    delete:
      tags: [Newsfeed]
      summary: Delete Newspost
      description: Deletes (or marks as deleted) a news post by ID.
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: News post deleted

  /newsfeed/{id}/history:
    get:
      tags: [Newsfeed]
      summary: History Newspost
      description: Returns the version history of a news post.
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: List of versions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewsPostRevision' # <-- UPDATED to point to the new schema

components:
  schemas:
    NewsPostCreate:
      type: object
      required: [title, summary, status, content, author]
      properties:
        title: { type: string }
        summary: { type: string }
        status:
          type: string
          enum: [draft, published, archived, deleted]
        content:
          $ref: '#/components/schemas/Content'
        featured_image:
          $ref: '#/components/schemas/FeaturedImage'
        author:
          $ref: '#/components/schemas/Author'
        publish_date:
          type: string
          format: date-time
          nullable: true
        expiration:
          $ref: '#/components/schemas/Expiration'
        permissions:
          $ref: '#/components/schemas/PermissionsRWX'
        settings:
          $ref: '#/components/schemas/Settings'

    NewsPostUpdate:
      allOf:
        - $ref: '#/components/schemas/NewsPostCreate'
      description: Same structure as Create for updates.

    NewsPostRead:
      type: object
      required: [id, version, title, summary, status, content, author, creationDate, lastModified]
      properties:
        id: { type: string }
        version: { type: integer }
        title: { type: string }
        summary: { type: string }
        status:
          type: string
          enum: [draft, published, archived, deleted]
        content:
          $ref: '#/components/schemas/Content'
        featured_image:
          $ref: '#/components/schemas/FeaturedImage'
        author:
          $ref: '#/components/schemas/Author'
        creationDate:
          type: string
          format: date-time
        publishDate:
          type: string
          format: date-time
          nullable: true
        lastModified:
          type: string
          format: date-time
        permissions:
          $ref: '#/components/schemas/PermissionsFlags'
        settings:
          $ref: '#/components/schemas/Settings'

    # --- NEW REVISION SCHEMA ---
    # This replaces the old NewsPostHistoryItem and matches your DTO
    NewsPostRevision:
      type: object
      required: [revisionNumber, revisionTimestamp, revisionType, newsPostState]
      properties:
        revisionNumber:
          type: integer
          description: The unique ID of the revision.
          example: 2
        revisionTimestamp:
          type: string
          format: date-time
          description: The timestamp when this revision was created.
          example: "2025-09-20T14:30:00Z"
        revisionType:
          type: string
          description: The type of change (ADD, MOD, DEL for create, modify, delete).
          enum: [ADD, MOD, DEL]
          example: "MOD"
        newsPostState:
          description: The complete state of the news post at this revision.
          $ref: '#/components/schemas/NewsPostRead' # Reuses the main read DTO for the snapshot

    Content:
      type: object
      required: [format, body]
      properties:
        format:
          type: string
          enum: [html]
        body:
          type: string

    FeaturedImage:
      type: object
      properties:
        url: { type: string, format: uri }
        alt_text: { type: string }
        caption: { type: string }

    Author:
      type: object
      required: [user_id, name]
      properties:
        user_id: { type: string }
        name: { type: string }
        avatar_url: { type: string, format: uri, nullable: true }

    Expiration:
      type: object
      properties:
        expires_at:
          type: string
          format: date-time
          nullable: true
        auto_archive:
          type: boolean
          nullable: true

    PrincipalRef:
      type: object
      required: [id, type, name]
      properties:
        id: { type: string }
        type:
          type: string
          enum: [user, group]
        name: { type: string }

    PermissionsRWX:
      type: object
      properties:
        read:
          type: array
          items: { $ref: '#/components/schemas/PrincipalRef' }
        write:
          type: array
          items: { $ref: '#/components/schemas/PrincipalRef' }
        delete:
          type: array
          items: { $ref: '#/components/schemas/PrincipalRef' }

    PermissionsFlags:
      type: object
      properties:
        update: { type: boolean }
        delete: { type: boolean }

    Settings:
      type: object
      properties:
        featured: { type: boolean }
        sticky: { type: boolean }
