spring:
  application:
    name: ASE-UserService
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2.console: path=/h2-console
  h2.console.enabled: true

server:
  error:
    include-message: always

