### Create a new newspost
PUT http://localhost:8080/api/newsposts
Content-Type: application/json

{ "title": "My First News Post3", "content": { "body": "Hello, world!" } }

> {%
    client.global.set("newspostId", response.body.id);
    client.test("Status is 200", function() {
        client.assert(response.status === 200);
    });
%}

### Create another newspost
PUT http://localhost:8080/api/newsposts
Content-Type: application/json

{ "title": "Second News Post", "content": { "body": "This is my second news post!" } }

> {% client.global.set("secondNewspostId", response.body.id); %}

### Update the second newspost
PUT http://localhost:8080/api/newsposts/{{secondNewspostId}}
Content-Type: application/json

{ "title": "Updated Second News Post", "content": { "body": "This is my updated second news post!" } }

### Delete the second newspost
DELETE http://localhost:8080/api/newsposts/{{secondNewspostId}}
Content-Type: application/json
