apiVersion: v1
kind: Service
metadata:
  name: newsfeed-service
  labels:
    app: newsfeed-service
spec:
  selector:
    app: newsfeed-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP