apiVersion: v1
kind: Service
metadata:
  name: backend-newsfeed
  labels:
    app: backend-newsfeed
spec:
  selector:
    app: backend-newsfeed
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP